### ISSUE TITLE
在propose external (majority)中输入hash后，页面报错

### ISSUE THREAD

**Issue by yakio** [darwinia-network/legacy-apps#107]
![image](https://user-images.githubusercontent.com/46353690/93843665-3079b800-fccd-11ea-8f99-a47ada490e95.png)

![image](https://user-images.githubusercontent.com/46353690/93843740-7cc4f800-fccd-11ea-8152-0bb5578e3533.png)

**Comment by WoeOm** [comment]
@AurevoirXavier crab缺少democracy模块
