### ISSUE TITLE
二次更改controller account的时候，controller account和stash account不能设置为相同的

### ISSUE THREAD

**Issue by yakio** [darwinia-network/legacy-apps#131]
![image](https://user-images.githubusercontent.com/46353690/94344026-e8e98800-004e-11eb-83ca-88014fdf9732.png)

**Comment by yakio** [comment]
仅仅是recommend， 但是 set按钮不可点击

**Comment by WoeOm** [comment]
因为和当前生效的为同一个controller，没有做任何修改

**Comment by yakio** [comment]
no，和当前生效不同的账号也不行，你测试看看🕶️
