### ISSUE TITLE
https://apps.darwinia.network/ don't save the account session from the polkadot wallet.

### ISSUE THREAD

**Issue by DiegoMaK** [darwinia-network/legacy-apps#188]
Hi,

I'm interacting with the https://apps.darwinia.network/ app, 

I do the following steps:

1. I import my json file for my polkadot wallet. the same json that I use in https://polkadot.js.org/apps/#/accounts
2. I check the network and I pick up the darwinia network mainnet.
3. I use the wormhole or bridge to transfer my RING to darwinia Network, using the public adress of my imported json.
4. I stack my ring and obtain KTON.

Everything looks good,.

But if I close the Chrome browser, or even if I press F5, my account dissapears. and I need to import the account again.

The bug then , is that the imported json accounts are not persisted in the webpage.

I try to create a direct account in darwinia Network, without importing it.  and this is persisted, is always open after I write the URL, or press F5

NOte: I try this on a macbook laptop. not sure if is relevant.
Chrome version:
Version 87.0.4280.88 (Official Build) (x86_64)
Mac Version: MacOS BIG SUR 11.0.1 (20B50)

**Comment by acgxv** [comment]
We'll check this.

And we recommend you use [polkadotjs plugin](https://chrome.google.com/webstore/detail/polkadot%7Bjs%7D-extension/mopnmbcafieddcagagdcbnhejhlodfdd) to manage your accounts.

**Comment by DiegoMaK** [comment]
Thanks.
I solved the issue changing settings in polkadotjs plugin.

1. I select my polkadot wallet.
2. I change the settings from  polkadot relay chain to allow use in any chain
3. Darwinia Network, never ask to import JSON again.
