### ISSUE TITLE
未成功展示存单中 cring/ckton 数量，也未展示锁定ring获得的kton数量

### ISSUE THREAD

**Issue by yakio** [darwinia-network/legacy-apps#20]
![image](https://user-images.githubusercontent.com/46353690/79745445-e154e300-833a-11ea-8801-af022433e4b4.png)

**Comment by WoeOm** [comment]
![image](https://user-images.githubusercontent.com/7368203/80300216-54dc7180-87cd-11ea-98c0-e7179bf7db42.png)

**Comment by WoeOm** [comment]
已修复
