### ISSUE TITLE
用CRAB账户领取Cring，在创建账户时，原始种子切换会造成地址变换，导致领取失败，能否固定选项或设置无法切换

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/legacy-apps#214]
![3 保存](https://user-images.githubusercontent.com/80877629/112436910-4aca4680-8d81-11eb-9cf2-fe5257d08357.jpg)

**Comment by acgxv** [comment]
?
```diff
- 领导
+ 领到
```
