### ISSUE TITLE
Decode for ethereumRelay.confirmedHeaderParcels: Option<EthereumRelayHeaderParcel> is not right on apps

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/legacy-apps#220]
![image](https://user-images.githubusercontent.com/1070122/115339598-b0222380-a1d7-11eb-924b-340b71b80bf7.png)

**Comment by hackfisher** [comment]
For reference:

https://darwinia.subscan.io/extrinsic/0x338dcd566b301e369b602329b11fa087f0363943b3a54971646ddec9232f26c0?event=2935996-2

**Comment by WoeOm** [comment]
fixed.
