### ISSUE TITLE
Apps中部分混淆概念调整 

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/legacy-apps#252]
![image](https://user-images.githubusercontent.com/80877629/127725257-d0293817-84df-459b-bdc2-2768f19c9a48.png)
![image](https://user-images.githubusercontent.com/80877629/127725262-1a92b658-f612-41a6-8fde-619e3a6abecb.png)

**Comment by WoeOm** [comment]
“仅显示定期锁定“—Only Term Deposits
