### ISSUE TITLE
Check(& polkadot.js PR?)

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/legacy-apps#255]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpangolin-rpc.darwinia.network%2F#/explorer/query/12494

**Comment by WoeOm** [comment]
https://github.com/polkadot-js/apps/pull/5930

**Comment by WoeOm** [comment]
![image](https://user-images.githubusercontent.com/7368203/128676178-44869bfa-51e5-459d-8da4-b75cbe7e0e42.png)
