### ISSUE TITLE
Can not open pangoro block page.

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/legacy-apps#273]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpangoro-rpc.darwinia.network#/explorer/query/0x66a0f092be4e5bed305700df9055db965987ffd9823a920b25c3f6a0050b2149

Sent following extrinsic in the block:

![image](https://user-images.githubusercontent.com/1070122/133600504-4779e5a9-8088-4f8d-aeca-02a13b7ffb95.png)

**Comment by sxlwar** [comment]
step:  go to network -> block details

local env

### pangoro

no error in the latest version

### darwinia

no error in the latest version

### crab

`RPC-CORE: queryStorageAt(keys: Vec<StorageKey>, at?: BlockHash): Vec<StorageChangeSet>:: Unable to decode storage indices.accounts: entry 2:: createType((AccountId,BalanceOf,bool)):: (AccountId,BalanceOf,Bool):: Decoded input doesn't match input, received 0xf83ee607164969887eaecab7e058ab3ba0f64c0cfe3f0b575fe45562cfc36bd500ca9a3b000000000000000000000000 (48 bytes), created 0xf83ee607164969887eaecab7e058ab3ba0f64c0cfe3f0b575fe45562cfc36bd500ca9a3b00000000000000000000000000 (49 bytes)`

### pangolin:

`VEC: Unable to decode on index 2 createType(ExtrinsicV4):: createType(Call):: Call: failed decoding bridgePangoroGrandpa.submitFinalityProof:: Struct: failed on args: {"finality_target":"BridgedHeader","justification":"GrandpaJustification"}:: decodeU8a: failed at 0xd6e63b6c2f4642fe… on finality_target: {"parent_Hash":"MillauBlockHash","number":"Compact<MillauBlockNumber>","state_root":"MillauBlockHash","extrinsics_root":"MillauBlockHash","digest":"MillauDigest"}:: decodeU8a: failed at 0xc3230bd53b0b421e… on digest: {"logs":"Vec<MillauDigestItem>"}:: decodeU8a: failed at 0xc3230bd53b0b421e… on logs: Vec<MillauDigestItem>:: Vec length 166932031403888831232930777539644141766773770963179868868495942883854096017605665105702076076603499702957807779348345292917539 exceeds 65536
`
