### ISSUE TITLE
polkadot.js types order wrong for OutboundLaneData

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/legacy-apps#277]
For reference, but notice that the order here might be wrong:
https://github.com/darwinia-network/parity-bridges-common/blob/main/deployments/types-wococo.json#L52-L56

Code:
https://github.com/darwinia-network/parity-bridges-common/blob/7be2b478b49bc8e87ddfe034076e9e80e2f126f6/primitives/messages/src/lib.rs#L278-L287

Better to make a pull request to polkadot js and parity-bridges-common
_Originally posted by @HackFisher in https://github.com/darwinia-network/darwinia-common/issues/829#issuecomment-922237363_

**Comment by sxlwar** [comment]
So the correct order would be something like this, right?

```json
"OutboundLaneData": {
     "oldest_unpruned_nonce": "MessageNonce",
     "latest_received_nonce": "MessageNonce",
     "latest_generated_nonce": "MessageNonce"
  }
```

Another question is, do OutboundLaneData anywhere else need to be changed?

**Comment by hackfisher** [comment]
> So the correct order would be something like this, right?
> 
> ```json
> "OutboundLaneData": {
>      "oldest_unpruned_nonce": "MessageNonce",
>      "latest_received_nonce": "MessageNonce",
>      "latest_generated_nonce": "MessageNonce"
>   }
> ```
> 
> Another question is, do OutboundLaneData anywhere else need to be changed?

Yes, but this is issue from upstream (polkadot.js and paritiy-bridge-common), better to PR to them.
