### ISSUE TITLE
Types Tracking

### ISSUE THREAD

**Issue by sxlwar** [darwinia-network/legacy-apps#282]
请在这里讨论所有关于类型的报错，请勿关闭此 issue

**Comment by sxlwar** [comment]
- [x] #281 https://github.com/darwinia-network/darwinia-common/pull/840 cc @AurevoirXavier #283

**Comment by sxlwar** [comment]
Polkadot apps：

voting ---> submit

`Uncaught (in promise) Error: Unable to decode storage system.account: entry 0:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x7b00000002000000010000000000000061c3113d3f2e0b000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes), created 0x7b00000002000000010000000000000061c3113d3f2e0b000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (112 bytes)
    at ta._newType (polkadot.01.09b53147.js:1)
    at ta._formatStorageSetEntry (polkadot.01.09b53147.js:1)
    at polkadot.01.09b53147.js:1
    at Array.reduce (<anonymous>)
    at ta._formatStorageSet (polkadot.01.09b53147.js:1)
    at ta._formatOutput (polkadot.01.09b53147.js:1)
    at Object.d [as callback] (polkadot.01.09b53147.js:1)
    at $.value (polkadot.01.09b53147.js:1)
    at WebSocket.value (polkadot.01.09b53147.js:1)`
    
---

From @AurevoirXavier 

Same with https://github.com/darwinia-network/apps/issues/282#issuecomment-927225478.
So I mark this as hidden.

**Comment by acgxv** [comment]
- [ ] These types became native-type. https://github.com/polkadot-js/api/pull/3995

**Comment by acgxv** [comment]
- [ ] https://github.com/darwinia-network/darwinia-common/pull/857
