### ISSUE TITLE
Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by boundless-forest** [darwinia-network/legacy-apps#286]
Darwinia Apps -> Pangolin network -> Staking Info will show such errors. I guess the reason is that type error or Polkadot js version needs an update. Need some help.

![image](https://user-images.githubusercontent.com/11801722/136535903-9572f49e-3298-4638-97da-87186bf18e2c.png)

**Comment by sxlwar** [comment]
Unfortunately, I have not reproduced this error on my local machine.  Could you pls provide more detail to help reproduce it?
I checked several places that contain the add keyword, and none of them seem to trigger this error
