### ISSUE TITLE
浏览器和节点信息

### ISSUE THREAD

**Issue by AlexChien** [darwinia-network/legacy-apps#30]
这几个栏目的信息有些可以合并或者重组，可以研究下

- 浏览器：目前的信息似乎只是验证人和候选人的信息，叫浏览器意思不匹配，而且可以合并入Staking/质押栏目中更直观
- 节点信息：这个似乎更应该叫浏览器，是链相关的信息，包括出块属性、相连的节点信息等等
- 质押：和质押相关的内容都应该包含进这个栏目中

**Comment by AlexChien** [comment]
似乎这个issue有了更新，看到了名字改为抵押总览

览器和抵押总览有必要再分开么？浏览器栏目仅多了候选人的信息列表，似乎可以通过在抵押总览栏目页面中通过增加并列或者增加一个Tab的方式实现。

目前的两个栏目内容显得冗余重复了。

**Comment by AlexChien** [comment]
抵押总览 里面看到候选人也有了。所以，现在的浏览器其实可以去掉了

**Comment by WoeOm** [comment]
浏览器是普通模式看的
抵押总览是开发者模式
