### ISSUE TITLE
what is the difference between  typegen and ApiPromise initialized from types.json

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/legacy-apps#36]
https://github.com/WoeOm/darwinia-polkadotjs-typegen

https://github.com/darwinia-network/darwinia.js/tree/master/packages/api

**Comment by WoeOm** [comment]
darwinia-polkadotjs-typegen 是metadata和自定义types生成的接口，来确定api.tx.*，api.query.*有哪些方法，不同metadata，*数量字段不同。 还有ts用的type定义；

darwinia.js/tree/master/packages/api应该是对polkadot.js的封装，包含了relay相关方法
