### ISSUE TITLE
交易签名页面-手续费计算问题，现在手续费显示都是0

### ISSUE THREAD

**Issue by yakio** [darwinia-network/legacy-apps#37]

**Comment by WoeOm** [comment]
rpc: payment_queryInfo
{"jsonrpc":"2.0","result":{"class":"normal","partialFee":"0","weight":500000000},"id":109}

**Comment by acgxv** [comment]
https://github.com/darwinia-network/darwinia/pull/445/commits/ee0a82ed958c2a8814c97a543a0f233bbe5ea4ce
