### ISSUE TITLE
Check total issuance 

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/legacy-apps#45]
I seems that the total issuance  in apps are different with the number on subscan.io

![bug001](https://user-images.githubusercontent.com/1070122/82678963-1a0b1380-9c7d-11ea-8ef1-16d78b55e1bf.png)

**Comment by WoeOm** [comment]
The total issuance is obtained from api.query.balances.totalIssuance, the value queried is 1,971,774,668.488 CRING.

 [https://crab.subscan.io/account](subscan)
![image](https://user-images.githubusercontent.com/7368203/82717987-4f8e1c00-9cd2-11ea-9251-bd32df3a2771.png)

These two values seem to be very close
