### ISSUE TITLE
Fee: Calculate the fee for extrinsic

### ISSUE THREAD

**Issue by yakio** [darwinia-network/legacy-apps#5]

**Comment by hackfisher** [comment]
The latest polkadot.js app seems to already support query transaction fees?

Following api in substrate might be related:

https://github.com/paritytech/substrate/blob/v2.0.0-alpha.3/bin/node/runtime/src/lib.rs#L801

**Comment by WoeOm** [comment]
Fetch the extrinsic fee by api.rpc.payment?.queryInfo
