### ISSUE TITLE
rpc grandpa.roundState()报错

### ISSUE THREAD

**Issue by WoeOm** [darwinia-network/legacy-apps#58]
![image](https://user-images.githubusercontent.com/7368203/83369964-89f16a80-a3f0-11ea-95e3-2f973cc8ed66.png)

**Comment by WoeOm** [comment]
https://github.com/polkadot-js/apps/commit/3314fded1d5c424977352d7e2327e60ce9024452

**Comment by acgxv** [comment]
Fixed in latest release.
