### ISSUE TITLE
Replace and update the favicon.ico

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/legacy-apps#7]
http://apps.darwinia.network/favicon.ico

**Comment by hackfisher** [comment]
And the title:

replace "Polkadot/Substrate Portal" with "Darwinia Apps Portal"

**Comment by WoeOm** [comment]
[replace "Polkadot/Substrate Portal" with "Darwinia Apps Portal"](https://github.com/darwinia-network/apps/commit/d1e044d1d265fff135db2c67fd755182fcdd05cd)
